name: Publicar proyecto

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: pnpm
          registry-url: https://npm.pkg.github.com
          scope: '@chem-gl'

      - name: Instalar dependencias
        run: pnpm install

      - name: Compilar
        run: pnpm build

      - name: Publicar
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: dist
