name: Publicar proyecto

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Publicar usando github-action-node-release
        uses: fdiesel/github-action-node-release@v3.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
