// tslint:disable
/**
 * API de Química
 * API para generar permutaciones de moléculas y obtener imágenes basadas en SMILES.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    Molecule,
} from './';

/**
 * @export
 * @interface GeneratedMolecule
 */
export interface GeneratedMolecule {
    /**
     * Identificador único de la molécula generada.
     * @type {number}
     * @memberof GeneratedMolecule
     */
    id?: number;
    /**
     * Nombre de la molécula generada.
     * @type {string}
     * @memberof GeneratedMolecule
     */
    nombreMolecula?: string;
    /**
     * @type {Molecule}
     * @memberof GeneratedMolecule
     */
    moleculaPrincipal?: Molecule;
    /**
     * @type {Molecule}
     * @memberof GeneratedMolecule
     */
    sustituyente?: Molecule;
    /**
     * Posición de la molécula principal.
     * @type {number}
     * @memberof GeneratedMolecule
     */
    posicionMoleculaPrincipal?: number;
    /**
     * Posición del sustituyente en la molécula generada.
     * @type {number}
     * @memberof GeneratedMolecule
     */
    posicionMoleculaSustituyente?: number;
}
