// tslint:disable
/**
 * API de Química
 * API para generar permutaciones de moléculas y obtener imágenes basadas en SMILES.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface Molecule
 */
export interface Molecule {
    /**
     * SMILES de la molécula.
     * @type {string}
     * @memberof Molecule
     */
    smile?: string;
    /**
     * Nombre de la molécula.
     * @type {string}
     * @memberof Molecule
     */
    nombre?: string;
    /**
     * Lista de átomos seleccionados.
     * @type {Array<number>}
     * @memberof Molecule
     */
    atomosSeleccionados?: Array<number>;
    /**
     * Indica si la molécula tiene hidrógenos implícitos.
     * @type {boolean}
     * @memberof Molecule
     */
    tieneHidrogenosImplicitos?: boolean;
}
